### ISSUE TITLE
Сравнение отечественных и мировых моделей: нужен аналог лидерборда Hugging Face!

### ISSUE THREAD

**Issue by xsa-dev** [ai-forever/gigachain#44]
### Проблема, которую вы хотите обсудить.

Привет, уважаемая команда!

Мы бы хотели предложить создать локальный лидерборд для сравнения моделей в России, аналогичный [лидерборду Hugging Face](https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard). Этот лидерборд поможет проводить сравнительную оценку между отечественными моделями и моделями с открытым исходным кодом, доступными за границей.

_Наши цели:_
1. Сравнивать производительность наших моделей с другими отечественными решениями.
2. Сравнивать наши модели с моделями с открытым исходным кодом из разных частей мира.
3. Предоставлять инсайты и данные, которые помогут нам улучшить наши модели.

Мы верим, что создание подобного лидерборда способствует прозрачности, развитию искусственного интеллекта и обработки естественного языка в России, а также обогатит общественное обсуждение. На данный момент, несмотря на существующий лидерборд от Hugging Face, отечественные модели отсутствуют на нем. Мы исследуем различные варианты создания такой платформы и будем благодарны за ваши идеи, комментарии и советы в этом вопросе.

Большое спасибо за внимание, и мы с нетерпением ждем обсуждения этой идеи и совместной работы!

### Предложение:

Создание локального лидерборда и вовлечение экспертов

**Comment by Rai220** [comment]
Теперь есть независимый лидерборд для сравнения русскоязычных моделей - https://mera.a-ai.ru/ru/leaderboard
