### ISSUE TITLE
DOC: Недоступен GigaChatEmbeddings в примере RAG

### ISSUE THREAD

**Issue by ZagidullinRuslanG** [ai-forever/gigachain#62]
### Проблема с существующей документацией:

В примере [https://github.com/ai-forever/gigachain/blob/master/docs/docs/use_cases/question_answering/gigachat_qa.ipynb](url) в разделе "Создание базы данных эмбеддингов" GigaChatEmbeddings недоступен.

**Comment by ZagidullinRuslanG** [comment]
Нужно поменять на from langchain_community.embeddings.gigachat import GigaChatEmbeddings

**Comment by Rai220** [comment]
Я проверил, должно работать и так и так.
Возможно, в прошлых версиях не работало.
