### ISSUE TITLE
WARNING:langchain_community.chat_models.gigachat:Giga generation stopped with reason: blacklist

### ISSUE THREAD

**Issue by AlexanderKozhevin** [ai-forever/gigachain#90]
### Контрольный список

- [X] Добавлен исчерпывающий заголовок.
- [X] Приложена ссылка на страницу, на которой обнаружена проблема (если применимо).

### Проблема с существующей документацией:

<img width="748" alt="Screenshot 2024-04-09 at 21 43 30" src="https://github.com/ai-forever/gigachain/assets/4464561/c140ef4a-9054-4a77-ad7b-dc31aa05136a">
Довольно странные ответы от LLM, по каким параментам оно вообще в blacklist попадает?

**Comment by Rai220** [comment]
Передал команде разработки LLM, поправят.
